### ISSUE TITLE
Verify wallet balance before making the transaction and processing it

### ISSUE THREAD

**Issue by dappsar** [P4-Games/ChatterPay-Backend#210]
In makeTransaction, the 'from' wallet balance for the requested token must be validated before proceeding with the operation.

**Comment by FixResolution** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.
