### ISSUE TITLE
Fix Token Swap and Refactor Balance Calculation

### ISSUE THREAD

**Issue by dappsar** [P4-Games/ChatterPay-Backend#230]
### Description:
There is an issue with the current token swap implementation where the transaction of the "input" token (the second transaction) is being set to `0`. This issue occurs when executing the swap, although the conversion logic in the contract is correct.

Additionally, the logic for calculating the final balances after the swap needs to be refactored to ensure it is more efficient and accurate.

### Current Issue:
- The second transaction (input token) is being left at `0`, even though the conversion in the contract is correct.
- The balance calculation for the tokens after the swap is not properly handled and needs refactoring.

### Expected Outcome:
- Ensure that the input token transaction (the second transaction) is correctly calculated and saved.
- Refactor the balance calculation logic to improve accuracy and performance.

### Tasks:
1. Investigate and fix the issue where the "input" token transaction is being set to `0`.
2. Refactor the balance calculation logic for both tokens (input and output) after the swap to ensure accurate results.
3. Test the functionality to ensure both input and output token transactions are correctly recorded and the balances are accurate.

### Notes:
- The contract logic for the conversion appears to be correct, but the issue seems to lie in how the token amounts are being handled in the backend after the swap.
- The calculation should correctly reflect the changes in token balances before and after the swap.

**Comment by Helpdeskalt1** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WT240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.
