### ISSUE TITLE
Descripción técnica del error de UserOperations

### ISSUE THREAD

**Issue by TomasDmArg** [P4-Games/ChatterPay-Backend#71]
Si vamos a buscar ayuda necesitamos tener una descripción tecnica del problema que enfrentamos con las UserOperations

https://caring-wholesaler-4ad.notion.site/ChatterPay-Technical-Report-User-Operation-Implementation-Errors-1129a315296180f09b1ede03f3113ba1?pvs=4

**Comment by dappsar** [comment]
duplicated with #72
